[build]
rustflags = ["-Ctarget-cpu=neoverse-n1", "-Ctarget-feature=+outline-atomics"]        # custom flags to pass to all compiler invocations

[env]
AWS_CONFIG_FILE= { value = ".aws/config", relative = true }
AWS_SHARED_CREDENTIALS_FILE={ value = ".aws/credentials", relative = true }